baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme="archie"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4