baseURL = 'https://qhtutorials.github.io/'
languageCode = 'en-us'
title = 'Quickly How Tutorials'
theme="archie"
publishDir = "docs"
copyright = "© Quickly How Tutorials"
paginate=3

[params]
   customcss = ["css/first.css"] 
 
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/qhtutorials/qhtutorials.github.io"

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Videos"
url = "/videos"
weight = 3

[[menu.main]]
name = "Slides"
url = "/slides"
weight = 4

[[menu.main]]
name = "PDFs"
url = "/pdfs"
weight = 5